services:
  # Backend (FastAPI Server)
  backend:
    build:
      context: ..
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8080:8080"
    env_file: ../.env
    networks:
      - rag-network
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 60
    #   start_period: 600s
    volumes:
      - ../AI:/app/AI
      - ../backend:/app/backend

  # Frontend (Streamlit App)
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8501:8501"
    env_file: ../.env
    environment:
      - BACKEND_URL=http://backend:8080
    # depends_on:
    #   backend:
    #     condition: service_healthy
    networks:
      - rag-network
    restart: unless-stopped
    volumes:
      - ../frontend:/app/frontend

networks:
  rag-network:
    driver: bridge